# Site settings
title: POSC 3410
subtitle: Quantitative Methods in Political Science
email: svmille@clemson.edu
description: "Both students and scholars alike are in political science as a result of their keen interest in politics. However, there is an increasing gap between how political science is applied by scholars and how it is understood by students. This class will aim to bridge that gap by introducing students to the science of political science. We will start with the basics, discussing concepts and variables before advancing toward regression. The course will conclude with very basic introductions to some advanced topics like non-normal responses, Bayesian inference, and post-estimation simulation. The overall goal of this class is to prepare students for upper division courses where peer-reviewed journal articles with multiple regressions and/or formal models are prominent."

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://posc3410.svmiller.com" # the base hostname & protocol for your site
syllabus: "http://posc3410.svmiller.com/syllabus/posc3410-fall2020-syllabus.pdf"
githubdir: "svmiller/posc3410"

# Author/user information
email: svmille@clemson.edu
twitter_username: stevenvmiller
github_username:  svmiller
authorurl: "http://svmiller.com"
address: |
    Department of Political Science
    232 Brackett Hall
    Clemson, SC 29634-1354


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
